name: Playwright Tests CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 1. Construimos tu imagen personalizada (la que tiene BasePage, Factories, etc.)
    - name: Build Docker Image
      run: docker build -t orangehrm-qa .

    # 2. Corremos los tests dentro del contenedor
    # Usamos -v para sacar los resultados del contenedor al runner de GitHub
    - name: Run Playwright tests in Docker
      run: |
        docker run --rm \
        -v ${{ github.workspace }}/allure-results:/app/allure-results \
        orangehrm-qa npx playwright test --workers=1
      continue-on-error: true

    # 3. Traemos el historial de reportes previos (para ver las gráficas de tendencia)
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: allure-history

    # 4. Generamos el reporte estático de Allure
    - name: Allure Report Action
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    # 5. Publicamos en GitHub Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages