name: Playwright Tests CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t orangehrm-qa .

    # Creamos la carpeta antes para evitar problemas de permisos de root
    - name: Prepare allure-results
      run: mkdir -p allure-results

    - name: Run Playwright tests in Docker
      run: |
        docker run --rm \
        -v ${{ github.workspace }}/allure-results:/app/allure-results \
        orangehrm-qa npx playwright test --workers=1
      continue-on-error: true

    # 💡 FIX: Cambiar permisos para que el runner pueda leer los resultados generados por Docker
    - name: Fix permissions
      if: always()
      run: sudo chown -R $USER:$USER allure-results

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages # Se recomienda llamarlo igual que la rama para evitar confusiones

    - name: Allure Report Action
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history # 💡 IMPORTANTE: Publicar la carpeta que contiene el historial acumulado
        publish_branch: gh-pages